name: Deploiement MkDocs GitHub Pages 

on: [workflow_dispatch]

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          
        - name: Test
          run: date

        - name: Install Python3
          uses: actions/setup-python@v5
          with: 
            python-version: '3.11'

        - name: Install MkDocs
          run: pip install -r requirements.txt

        - name: Build MkDocs
          run: mkdocs build

        - name: Debug
          run: ls

        - name: Artifact upload
          uses: actions/upload-artifact@v4
          with:
            name: site
            path: site

    Deploiement:
        runs-on: ubuntu-latest
        permissions:
            pages: write     
            id-token: write 
        environment:
                name: github-pages
                url: ${{ steps.deployment.outputs.page_url }}
        steps:
        - name: ls
          run: ls

        - name: Artifact download
          uses: actions/download-artifact@v4.1.7
          with: 
            name: site

        - name: ls et creer dossier _site
          run: |
              ls -alh
              mkdir _site
              ls
  
        - name: Deplacer dans _site en html
          run: |          
              mv $(ls --ignore=_site) _site/
              ls _site

        - name: Fix permissions
          run: |
            chmod -c -R +rX "_site/" | while read line; do
              echo "::warning title=Invalid file permissions automatically fixed::$line"
            done
    
        - name: Upload-pages-artifac
          uses: actions/upload-pages-artifact@v3 
              
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
            
        needs: Build
    
